services:
  - type: web
    name: nextjs-app
    runtime: node
    repo: https://github.com/tuproject/nextjs
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_POCKETBASE_URL
        value: https://nays-dream.pockethost.io
      - key: NEXT_PUBLIC_PHONE_NUMBER
        sync: false # Puedes definirlo en el dashboard de Render
